# Generated by Django 4.2.5 on 2023-10-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trail",
            name="location",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
