# Generated by Django 4.2.5 on 2023-10-04 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trail_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('break_type', models.CharField(choices=[('W', 'Water'), ('L', 'Lunch'), ('S', 'Snack'), ('P', 'Picture')], default='W', max_length=1)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trail')),
            ],
        ),
    ]
