# Generated by Django 4.2.5 on 2023-10-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_hiking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiking',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='hiking',
            name='date',
            field=models.DateField(verbose_name='hiking date'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trail')),
            ],
        ),
    ]
