# Generated by Django 4.2.5 on 2023-10-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_hiking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiking',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
