# Generated by Django 4.2.5 on 2023-10-05 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_hiking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiking',
            name='created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
