# Generated by Django 4.2.5 on 2023-10-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_hiking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiking',
            options={'ordering': ['-date', '-created']},
        ),
    ]
