# Generated by Django 4.2.5 on 2023-10-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_hiking_date'),
        ('main_app', '0011_alter_hiking_options'),
    ]

    operations = [
    ]
