# Generated by Django 4.2.5 on 2023-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20231006_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiking',
            name='date',
            field=models.DateField(verbose_name='hiking date'),
        ),
    ]
